const $ = (selector, root = document) => root.querySelector(selector);
const app = document.getElementById('app');
const today = new Date(); today.setHours(0,0,0,0);
const uid = () => crypto.randomUUID();
const isoNow = () => new Date().toISOString();
const toDate = (value) => value ? new Date(`${value}T00:00:00`) : null;
const fmtDate = (value) => value ? new Intl.DateTimeFormat('de-DE').format(new Date(value)) : '—';
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const storeKey = 'simple-crm-data-v1';
const emptyData = { companies: [], contacts: [], followUps: [] };
let data = loadData();
let view = 'dashboard';
let selectedCompanyId = null;
let filter = 'offen';

function loadData() {
  const saved = localStorage.getItem(storeKey);
  if (saved) return JSON.parse(saved);
  const now = isoNow();
  return {
    companies: [{ id: uid(), name: 'Muster GmbH', website: 'https://beispiel.de', industry: 'Beratung', status: 'Lead', notes: 'Erster Kontakt über Empfehlung.', createdAt: now, updatedAt: now }],
    contacts: [], followUps: []
  };
}
function saveData() { localStorage.setItem(storeKey, JSON.stringify(data)); render(); }
function companyName(id) { return data.companies.find(c => c.id === id)?.name || 'Keine Firma'; }
function contactName(id) { const c = data.contacts.find(x => x.id === id); return c ? `${c.firstName} ${c.lastName}` : '—'; }
function isOverdue(f) { const d = toDate(f.dueDate); return f.status === 'Offen' && d && d < today; }
function isToday(f) { const d = toDate(f.dueDate); return d && d.getTime() === today.getTime(); }
function isThisWeek(f) { const d = toDate(f.dueDate); if (!d) return false; const end = new Date(today); end.setDate(today.getDate() + 7); return d >= today && d <= end; }
function companyFollowUps(id) { return data.followUps.filter(f => f.companyId === id); }
function lastActivity(id) { return companyFollowUps(id).sort((a,b) => new Date(b.updatedAt)-new Date(a.updatedAt))[0]; }
function nextFollowUp(id) { return companyFollowUps(id).filter(f => f.status === 'Offen').sort((a,b) => (a.dueDate || '9999').localeCompare(b.dueDate || '9999'))[0]; }

function render() {
  app.innerHTML = `<div class="app-shell"><aside class="sidebar">${brand()}${nav()}</aside><div><header class="mobile-topbar">${brand()}<button class="btn" id="menuBtn">Menü</button></header><div class="mobile-menu" id="mobileMenu">${nav()}</div><main class="main"><div class="content">${route()}</div></main></div></div>`;
  $('#menuBtn')?.addEventListener('click', () => $('#mobileMenu').classList.toggle('open'));
  document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => { view = b.dataset.view; selectedCompanyId = null; render(); }));
  bindActions();
}
function brand() { return `<div class="brand"><span class="brand-mark">CRM</span><span>Einfaches CRM</span></div>`; }
function nav() { return `<nav class="nav">${[['dashboard','Übersicht'],['companies','Firmen'],['contacts','Kontakte'],['followups','Follow-ups']].map(([k,l]) => `<button class="${view===k?'active':''}" data-view="${k}">${l}</button>`).join('')}</nav>`; }
function route() { if (view === 'companies') return companiesPage(); if (view === 'contacts') return contactsPage(); if (view === 'followups') return followUpsPage(); if (view === 'companyDetail') return companyDetailPage(); return dashboardPage(); }
function header(title, text, action = '') { return `<div class="page-header"><div><h1>${title}</h1><p>${text}</p></div><div class="actions">${action}</div></div>`; }
function empty(text) { return `<div class="empty">${text}</div>`; }
function statusBadge(status) { const cls = status === 'Erledigt' ? 'done' : status === 'Offen' ? 'open' : status === 'Aktiv' ? 'active' : status === 'Kunde' ? 'customer' : status === 'Inaktiv' ? 'inactive' : ''; return `<span class="badge ${cls}">${status}</span>`; }
function priorityBadge(p) { return `<span class="badge ${p === 'Hoch' ? 'high' : ''}">${p}</span>`; }

function dashboardPage() {
  const open = data.followUps.filter(f => f.status === 'Offen').sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));
  const overdue = open.filter(isOverdue).length;
  return `${header('Übersicht','Was muss ich als Nächstes tun?', '<button class="btn primary" data-open-follow>Follow-up hinzufügen</button>')}
  <section class="grid four">${[['Firmen gesamt',data.companies.length],['Kontakte gesamt',data.contacts.length],['Offene Follow-ups',open.length],['Überfällige Follow-ups',overdue]].map(s=>`<div class="card stat"><span class="kv">${s[0]}</span><strong>${s[1]}</strong></div>`).join('')}</section>
  <section class="grid two" style="margin-top:18px"><div class="card"><h2>Offene Follow-ups</h2>${open.length ? followCards(open) : empty('Keine offenen Follow-ups')}</div><div class="card"><h2>Heute fällig</h2>${open.filter(isToday).length ? followCards(open.filter(isToday)) : empty('Heute ist nichts fällig')}</div></section>
  <section class="card" style="margin-top:18px"><h2>Kürzlich aktualisierte Firmen</h2>${data.companies.length ? followCompanyList(data.companies.slice().sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5)) : empty('Noch keine Firmen vorhanden')}</section>`;
}
function followCards(items) { return `<div class="timeline">${items.map(f => `<article class="follow-card ${isOverdue(f)?'overdue':''}"><div class="actions"><strong>${escapeHtml(f.title)}</strong>${isOverdue(f)?'<span class="badge overdue">Überfällig</span>':''}</div><span class="kv">${fmtDate(f.dueDate)} · ${companyName(f.companyId)} · ${contactName(f.contactId)}</span><div>${statusBadge(f.status)} ${priorityBadge(f.priority)} <span class="badge">${f.type}</span></div><div class="actions"><button class="btn" data-edit-follow="${f.id}">Bearbeiten</button>${f.status==='Offen'?`<button class="btn" data-done="${f.id}">Als erledigt markieren</button>`:`<button class="btn" data-reopen="${f.id}">Wieder öffnen</button>`}<button class="btn danger" data-delete-follow="${f.id}">Löschen</button></div></article>`).join('')}</div>`; }
function followCompanyList(items) { return `<div class="timeline">${items.map(c => `<article class="follow-card"><strong>${escapeHtml(c.name)}</strong><span class="kv">${statusBadge(c.status)} · Letzte Aktivität: ${fmtDate(lastActivity(c.id)?.updatedAt || c.updatedAt)}</span><button class="btn" data-company-detail="${c.id}">Firmendetails öffnen</button></article>`).join('')}</div>`; }

function companiesPage() { return `${header('Firmen','Organisationen hinzufügen, bearbeiten und verwalten.', '<button class="btn primary" data-open-company>Firma hinzufügen</button>')}<div class="card">${data.companies.length ? companyTable() : empty('Noch keine Firmen vorhanden')}</div>`; }
function companyTable() { const rows = data.companies.map(c => { const next=nextFollowUp(c.id), last=lastActivity(c.id); return `<tr><td><button class="btn" data-company-detail="${c.id}">${escapeHtml(c.name)}</button></td><td>${statusBadge(c.status)}</td><td>${fmtDate(last?.updatedAt || c.updatedAt)}</td><td>${next?escapeHtml(next.title):'—'}</td><td>${fmtDate(next?.dueDate)}</td><td>${data.contacts.filter(x=>x.companyId===c.id).length}</td><td class="actions"><button class="btn" data-edit-company="${c.id}">Bearbeiten</button><button class="btn danger" data-delete-company="${c.id}">Löschen</button></td></tr>`; }).join(''); return `<div class="table-wrap responsive"><table><thead><tr><th>Firma</th><th>Status</th><th>Letzte Aktivität</th><th>Nächster Follow-up</th><th>Fällig am</th><th>Anzahl Kontakte</th><th>Aktionen</th></tr></thead><tbody>${rows}</tbody></table></div><div class="mobile-cards">${followCompanyList(data.companies)}</div>`; }
function companyDetailPage() { const c=data.companies.find(x=>x.id===selectedCompanyId); if(!c) return empty('Firma wurde nicht gefunden'); const contacts=data.contacts.filter(x=>x.companyId===c.id); const fs=companyFollowUps(c.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); return `${header(c.name,'Firmendetails, Kontakte und Verlauf.', '<button class="btn" data-view="companies">Zurück</button><button class="btn primary" data-open-contact>Kontakt hinzufügen</button><button class="btn primary" data-open-follow>Follow-up hinzufügen</button>')}<section class="grid two"><div class="card"><h2>Firmenkopf</h2><p>${statusBadge(c.status)}</p><p><strong>Website:</strong> ${c.website ? `<a href="${escapeHtml(c.website)}" target="_blank">${escapeHtml(c.website)}</a>` : '—'}</p><p><strong>Branche:</strong> ${escapeHtml(c.industry || '—')}</p><p>${escapeHtml(c.notes || 'Keine Notizen')}</p></div><div class="card"><h2>Verknüpfte Kontakte</h2>${contacts.length ? contacts.map(k=>`<p>${escapeHtml(k.firstName)} ${escapeHtml(k.lastName)} · ${escapeHtml(k.role||'Keine Rolle')}</p>`).join('') : empty('Noch keine Kontakte vorhanden')}</div></section><section class="grid two" style="margin-top:18px"><div class="card"><h2>Offene Follow-ups</h2>${fs.filter(f=>f.status==='Offen').length ? followCards(fs.filter(f=>f.status==='Offen')) : empty('Keine offenen Follow-ups')}</div><div class="card"><h2>Follow-up-Verlauf</h2>${fs.length ? followCards(fs) : empty('Noch keine Follow-ups vorhanden')}</div></section>`; }

function contactsPage() { return `${header('Kontakte','Personen erfassen und mit Firmen verknüpfen.', '<button class="btn primary" data-open-contact>Kontakt hinzufügen</button>')}<div class="card">${data.contacts.length ? contactTable() : empty('Noch keine Kontakte vorhanden')}</div>`; }
function contactTable() { return `<div class="table-wrap responsive"><table><thead><tr><th>Name</th><th>Firma</th><th>Rolle</th><th>E-Mail</th><th>Telefon</th><th>Aktionen</th></tr></thead><tbody>${data.contacts.map(c=>`<tr><td>${escapeHtml(c.firstName)} ${escapeHtml(c.lastName)}</td><td><button class="btn" data-company-detail="${c.companyId}">${companyName(c.companyId)}</button></td><td>${escapeHtml(c.role||'—')}</td><td>${escapeHtml(c.email||'—')}</td><td>${escapeHtml(c.phone||'—')}</td><td class="actions"><button class="btn" data-edit-contact="${c.id}">Bearbeiten</button><button class="btn danger" data-delete-contact="${c.id}">Löschen</button></td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${data.contacts.map(c=>`<article class="follow-card"><strong>${escapeHtml(c.firstName)} ${escapeHtml(c.lastName)}</strong><span class="kv">${companyName(c.companyId)} · ${escapeHtml(c.role||'Keine Rolle')}</span><div class="actions"><button class="btn" data-edit-contact="${c.id}">Bearbeiten</button><button class="btn danger" data-delete-contact="${c.id}">Löschen</button></div></article>`).join('')}</div>`; }
function followUpsPage() { let items=data.followUps.filter(f=> filter==='offen'?f.status==='Offen':filter==='erledigt'?f.status==='Erledigt':filter==='überfällig'?isOverdue(f):filter==='heute'?isToday(f):filter==='woche'?isThisWeek(f):true); return `${header('Follow-ups','Aufgaben, Gespräche und nächste Schritte verwalten.', '<button class="btn primary" data-open-follow>Follow-up hinzufügen</button>')}<div class="filters">${[['alle','Alle'],['offen','Offen'],['erledigt','Erledigt'],['überfällig','Überfällig'],['heute','Heute fällig'],['woche','Diese Woche']].map(([k,l])=>`<button class="btn ${filter===k?'primary':''}" data-filter="${k}">${l}</button>`).join('')}<select id="priorityFilter"><option value="">Nach Priorität</option><option>Niedrig</option><option>Mittel</option><option>Hoch</option></select><select id="companyFilter"><option value="">Nach Firma</option>${data.companies.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select></div><div class="card">${items.length ? followCards(items) : empty('Keine Follow-ups gefunden')}</div>`; }

function bindActions() {
  document.querySelectorAll('[data-open-company]').forEach(b=>b.onclick=()=>openCompanyForm());
  document.querySelectorAll('[data-edit-company]').forEach(b=>b.onclick=()=>openCompanyForm(data.companies.find(c=>c.id===b.dataset.editCompany)));
  document.querySelectorAll('[data-delete-company]').forEach(b=>b.onclick=()=>confirmDelete('Firma löschen?',()=>{data.companies=data.companies.filter(c=>c.id!==b.dataset.deleteCompany);data.contacts=data.contacts.filter(c=>c.companyId!==b.dataset.deleteCompany);data.followUps=data.followUps.filter(f=>f.companyId!==b.dataset.deleteCompany);saveData();}));
  document.querySelectorAll('[data-company-detail]').forEach(b=>b.onclick=()=>{selectedCompanyId=b.dataset.companyDetail;view='companyDetail';render();});
  document.querySelectorAll('[data-open-contact]').forEach(b=>b.onclick=()=>openContactForm()); document.querySelectorAll('[data-edit-contact]').forEach(b=>b.onclick=()=>openContactForm(data.contacts.find(c=>c.id===b.dataset.editContact))); document.querySelectorAll('[data-delete-contact]').forEach(b=>b.onclick=()=>confirmDelete('Kontakt löschen?',()=>{data.contacts=data.contacts.filter(c=>c.id!==b.dataset.deleteContact);saveData();}));
  document.querySelectorAll('[data-open-follow]').forEach(b=>b.onclick=()=>openFollowForm()); document.querySelectorAll('[data-edit-follow]').forEach(b=>b.onclick=()=>openFollowForm(data.followUps.find(f=>f.id===b.dataset.editFollow))); document.querySelectorAll('[data-delete-follow]').forEach(b=>b.onclick=()=>confirmDelete('Follow-up löschen?',()=>{data.followUps=data.followUps.filter(f=>f.id!==b.dataset.deleteFollow);saveData();})); document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.done); f.status='Erledigt'; f.completedAt=isoNow(); f.updatedAt=isoNow(); saveData();}); document.querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.reopen); f.status='Offen'; f.completedAt=''; f.updatedAt=isoNow(); saveData();});
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();}); $('#priorityFilter')?.addEventListener('change', e=>{ if(e.target.value) { data.followUps=data.followUps; $('.card').innerHTML=followCards(data.followUps.filter(f=>f.priority===e.target.value)) || empty('Keine Follow-ups gefunden'); }}); $('#companyFilter')?.addEventListener('change', e=>{ if(e.target.value) $('.card').innerHTML=followCards(data.followUps.filter(f=>f.companyId===e.target.value)) || empty('Keine Follow-ups gefunden'); });
}
function modal(title, body) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="btn" data-close>Schließen</button></div>${body}</div></div>`); $('[data-close]').onclick=()=>$('.modal-backdrop').remove(); }
function fields(obj, type) { if(type==='company') return `<div class="form-grid"><label class="field">Name*<input name="name" required value="${escapeHtml(obj?.name||'')}"></label><label class="field">Status<select name="status">${['Lead','Aktiv','Kunde','Inaktiv'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Website<input name="website" value="${escapeHtml(obj?.website||'')}"></label><label class="field">Branche<input name="industry" value="${escapeHtml(obj?.industry||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`; if(type==='contact') return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Rolle<input name="role" value="${escapeHtml(obj?.role||'')}"></label><label class="field">Vorname*<input name="firstName" required value="${escapeHtml(obj?.firstName||'')}"></label><label class="field">Nachname*<input name="lastName" required value="${escapeHtml(obj?.lastName||'')}"></label><label class="field">E-Mail<input name="email" type="email" value="${escapeHtml(obj?.email||'')}"></label><label class="field">Telefon<input name="phone" value="${escapeHtml(obj?.phone||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`; return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Kontakt<select name="contactId"><option value="">Kein Kontakt</option>${data.contacts.map(c=>`<option value="${c.id}" ${obj?.contactId===c.id?'selected':''}>${escapeHtml(c.firstName)} ${escapeHtml(c.lastName)}</option>`).join('')}</select></label><label class="field">Typ<select name="type">${['Anruf','E-Mail','Meeting','Notiz','Aufgabe'].map(s=>`<option ${obj?.type===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Priorität<select name="priority">${['Niedrig','Mittel','Hoch'].map(s=>`<option ${obj?.priority===s?'selected':''}>${s}</option>`)}</select></label><label class="field full">Titel*<input name="title" required value="${escapeHtml(obj?.title||'')}"></label><label class="field">Fällig am<input name="dueDate" type="date" value="${escapeHtml(obj?.dueDate||'')}"></label><label class="field">Status<select name="status">${['Offen','Erledigt'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field full">Beschreibung<textarea name="description">${escapeHtml(obj?.description||'')}</textarea></label></div>`; }
function handleForm(form, obj, collection, mapper) { const fd=Object.fromEntries(new FormData(form)); if(!form.checkValidity()){form.reportValidity();return;} const now=isoNow(); if(obj) Object.assign(obj, mapper(fd), {updatedAt: now}); else data[collection].push({id:uid(), ...mapper(fd), createdAt:now, updatedAt:now}); $('.modal-backdrop').remove(); saveData(); }
function openCompanyForm(obj) { modal(obj?'Firma bearbeiten':'Firma hinzufügen', `<form id="form">${fields(obj,'company')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'companies',x=>x);}; }
function openContactForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Kontakt bearbeiten':'Kontakt hinzufügen', `<form id="form">${fields(obj,'contact')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'contacts',x=>x);}; }
function openFollowForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Follow-up bearbeiten':'Follow-up hinzufügen', `<form id="form">${fields(obj,'follow')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'followUps',x=>({...x, completedAt:x.status==='Erledigt'?(obj?.completedAt||isoNow()):''}));}; }
function confirmDelete(message, cb) { if (confirm(`${message}\nDiese Aktion kann nicht rückgängig gemacht werden.`)) cb(); }
render();
