const $ = (selector, root = document) => root.querySelector(selector);
const app = document.getElementById('app');
const today = new Date(); today.setHours(0,0,0,0);
const uid = () => crypto.randomUUID();
const isoNow = () => new Date().toISOString();
const toDate = (value) => value ? new Date(`${value}T00:00:00`) : null;
const fmtDate = (value) => value ? new Intl.DateTimeFormat('de-DE').format(new Date(value)) : '—';
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const storeKey = 'simple-crm-data-v1';
let data = loadData();
let view = 'dashboard';
let selectedCompanyId = null;
let selectedContactId = null;
let tableState = { companies: { q:'', sort:'name', dir:'asc' }, contacts: { q:'', status:'', priority:'', sort:'name', dir:'asc' }, followups: { q:'', status:'', priority:'', companyId:'', contactId:'', due:'', sort:'dueDate', dir:'asc' }, timelineDir: 'desc' };
const icons = { dashboard:'M3 13h8V3H3v10Zm10 8h8V3h-8v18ZM3 21h8v-6H3v6Z', companies:'M3 21h18M5 21V7l8-4v18M19 21V11l-6-3M9 9h1M9 13h1M9 17h1M15 13h1M15 17h1', contacts:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75', followups:'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2ZM8 14h.01M12 14h.01M16 14h.01', plus:'M12 5v14M5 12h14', search:'m21 21-4.3-4.3M10 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16Z', edit:'M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5Z', trash:'M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15', call:'M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13 1 .36 1.98.7 2.91a2 2 0 0 1-.45 2.11L8.09 10a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.93.34 1.9.57 2.91.7A2 2 0 0 1 22 16.92Z', mail:'M4 4h16v16H4zM22 6l-10 7L2 6', meeting:'M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM23 21v-2a4 4 0 0 0-3-3.87', note:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8M8 17h6', task:'M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11', arrow:'M5 12h14M13 5l7 7-7 7', empty:'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3' };
function icon(name) { return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name] || icons.empty}"/></svg>`; }
function loadData() { const saved = localStorage.getItem(storeKey); if (saved) return JSON.parse(saved); const now = isoNow(); return { companies: [{ id: uid(), name: 'Muster GmbH', website: 'https://beispiel.de', industry: 'Beratung', status: 'Lead', notes: 'Erster Kontakt über Empfehlung.', createdAt: now, updatedAt: now }], contacts: [], followUps: [] }; }
function saveData() { localStorage.setItem(storeKey, JSON.stringify(data)); render(); }
const fullName = c => c ? `${c.firstName || ''} ${c.lastName || ''}`.trim() : '—';
function companyName(id) { return data.companies.find(c => c.id === id)?.name || 'Keine Firma'; }
function contactName(id) { return fullName(data.contacts.find(x => x.id === id)); }
function contactById(id) { return data.contacts.find(c => c.id === id); }
function isOverdue(f) { const d = toDate(f.dueDate); return f.status === 'Offen' && d && d < today; }
function isToday(f) { const d = toDate(f.dueDate); return d && d.getTime() === today.getTime(); }
function isThisWeek(f) { const d = toDate(f.dueDate); if (!d) return false; const end = new Date(today); end.setDate(today.getDate() + 7); return d >= today && d <= end; }
function companyFollowUps(id) { return data.followUps.filter(f => f.companyId === id); }
function contactFollowUps(id) { return data.followUps.filter(f => f.contactId === id); }
function lastActivity(id) { return companyFollowUps(id).sort((a,b) => new Date(b.updatedAt)-new Date(a.updatedAt))[0]; }
function contactLastActivity(id) { return contactFollowUps(id).sort((a,b) => new Date(b.updatedAt)-new Date(a.updatedAt))[0]; }
function nextFollowUpByCompany(id) { return companyFollowUps(id).filter(f => f.status === 'Offen').sort(byField('dueDate','asc'))[0]; }
function nextFollowUpByContact(id) { return contactFollowUps(id).filter(f => f.status === 'Offen').sort(byField('dueDate','asc'))[0]; }
function priorityRank(p) { return { Hoch: 3, Mittel: 2, Niedrig: 1 }[p] || 0; }
function byField(field, dir='asc') { return (a,b) => { const mult = dir === 'desc' ? -1 : 1; let av = field === 'priority' ? priorityRank(a.priority) : (a[field] || ''); let bv = field === 'priority' ? priorityRank(b.priority) : (b[field] || ''); return String(av).localeCompare(String(bv), 'de', { numeric: true }) * mult; }; }
function render() { app.innerHTML = `<div class="app-shell"><aside class="sidebar">${brand()}${nav()}</aside><main class="main"><div class="content">${route()}</div></main></div>`; document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => { view = b.dataset.view; selectedCompanyId = null; selectedContactId = null; render(); })); bindActions(); }
function brand() { return `<div class="brand"><span class="brand-mark">${icon('dashboard')}</span><span>Einfaches CRM</span></div>`; }
function nav() { return `<nav class="nav">${[['dashboard','Übersicht','dashboard'],['companies','Firmen','companies'],['contacts','Kontakte','contacts'],['followups','Follow-ups','followups']].map(([k,l,i]) => `<button class="${view===k?'active':''}" data-view="${k}">${icon(i)}<span>${l}</span></button>`).join('')}</nav>`; }
function route() { if (view === 'companies') return companiesPage(); if (view === 'contacts') return contactsPage(); if (view === 'followups') return followUpsPage(); if (view === 'companyDetail') return companyDetailPage(); if (view === 'contactDetail') return contactDetailPage(); return dashboardPage(); }
function header(title, text, action = '') { return `<div class="page-header"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(text)}</p></div><div class="actions">${action}</div></div>`; }
function empty(text) { return `<div class="empty">${icon('empty')}<strong>${escapeHtml(text)}</strong><span>Erstelle neue Einträge oder passe deine Filter an.</span></div>`; }
function statusBadge(status='—') { const cls = status === 'Erledigt' ? 'done' : status === 'Offen' ? 'open' : status === 'Aktiv' ? 'active' : status === 'Kunde' ? 'customer' : status === 'Inaktiv' ? 'inactive' : ''; return `<span class="badge ${cls}">${escapeHtml(status)}</span>`; }
function priorityBadge(p='—') { return `<span class="badge ${p === 'Hoch' ? 'high' : p === 'Mittel' ? 'medium' : ''}">${escapeHtml(p)}</span>`; }
function dashboardPage() { const open = data.followUps.filter(f => f.status === 'Offen').sort(byField('dueDate')); const overdue = open.filter(isOverdue).length; return `${header('Übersicht','Fokus auf aktuelle Firmen, Kontakte und nächste Schritte.', `<button class="btn primary" data-open-follow>${icon('plus')}Follow-up hinzufügen</button>`)}<section class="grid four">${[['Firmen',data.companies.length,'companies'],['Kontakte',data.contacts.length,'contacts'],['Offen',open.length,'followups'],['Überfällig',overdue,'followups']].map(s=>`<button class="card stat" data-view="${s[2]}">${icon(s[2])}<span class="kv">${s[0]}</span><strong>${s[1]}</strong></button>`).join('')}</section><section class="card" style="margin-top:18px"><h2>Nächste Follow-ups</h2>${open.length ? followUpsTable(open.slice(0,8), false) : empty('Keine offenen Follow-ups')}</section>`; }
function toolbar(kind, placeholder, extra='') { const s=tableState[kind]; return `<div class="filters"><label class="search-field">${icon('search')}<input data-table-search="${kind}" placeholder="${placeholder}" value="${escapeHtml(s.q)}"></label>${extra}</div>`; }
function sortHead(kind, field, label) { const s=tableState[kind]; return `<button class="sort-head ${s.sort===field?'active':''}" data-sort-kind="${kind}" data-sort-field="${field}">${label}${s.sort===field ? (s.dir==='asc'?' ↑':' ↓') : ''}</button>`; }
function companiesPage() { const s=tableState.companies; const q=s.q.toLowerCase(); const items=data.companies.filter(c=>[c.name,c.status,c.industry,c.website].join(' ').toLowerCase().includes(q)).sort((a,b)=>{ const row = c => ({...c, contacts:data.contacts.filter(x=>x.companyId===c.id).length, nextDue:nextFollowUpByCompany(c.id)?.dueDate || '9999-99-99', last:lastActivity(c.id)?.updatedAt || c.updatedAt}); return byField(s.sort,s.dir)(row(a),row(b)); }); return `${header('Firmen','Alle Organisationen als klare Tabelle.', `<button class="btn primary" data-open-company>${icon('plus')}Firma hinzufügen</button>`)}${toolbar('companies','Firmen suchen ...')}<div class="table-card">${items.length ? companyTable(items) : empty('Keine Firmen gefunden')}</div>`; }
function companyTable(items) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('companies','name','Firma')}</th><th>${sortHead('companies','status','Status')}</th><th>${sortHead('companies','industry','Branche')}</th><th>${sortHead('companies','last','Letzte Aktivität')}</th><th>${sortHead('companies','nextDue','Nächster Follow-up')}</th><th>${sortHead('companies','contacts','Kontakte')}</th><th>Aktionen</th></tr></thead><tbody>${items.map(c => { const next=nextFollowUpByCompany(c.id), last=lastActivity(c.id); return `<tr class="click-row" data-company-detail="${c.id}"><td><strong>${escapeHtml(c.name)}</strong><div class="kv">${escapeHtml(c.website || 'Keine Website')}</div></td><td>${statusBadge(c.status)}</td><td>${escapeHtml(c.industry || '—')}</td><td>${fmtDate(last?.updatedAt || c.updatedAt)}</td><td>${next ? `${escapeHtml(next.title)}<div class="kv">${fmtDate(next.dueDate)}</div>` : '—'}</td><td>${data.contacts.filter(x=>x.companyId===c.id).length}</td><td class="actions"><button class="btn" data-edit-company="${c.id}">${icon('edit')}</button><button class="btn danger" data-delete-company="${c.id}">${icon('trash')}</button></td></tr>`; }).join('')}</tbody></table></div>`; }
function companyDetailPage() { const c=data.companies.find(x=>x.id===selectedCompanyId); if(!c) return empty('Firma wurde nicht gefunden'); const contacts=data.contacts.filter(x=>x.companyId===c.id); return `${header(c.name,'Firmendetails und zugehörige Kontakte.', '<button class="btn" data-view="companies">Zurück</button><button class="btn primary" data-open-contact>'+icon('plus')+'Kontakt hinzufügen</button>')}<section class="detail-grid"><div class="card"><h2>Profil</h2><p>${statusBadge(c.status)}</p><p><strong>Website:</strong> ${c.website ? `<a href="${escapeHtml(c.website)}" target="_blank">${escapeHtml(c.website)}</a>` : '—'}</p><p><strong>Branche:</strong> ${escapeHtml(c.industry || '—')}</p><p>${escapeHtml(c.notes || 'Keine Notizen')}</p></div><div class="card wide"><h2>Kontakte</h2>${contacts.length ? contactTable(contacts, false) : empty('Noch keine Kontakte vorhanden')}</div></section>`; }
function contactsPage() { const s=tableState.contacts; const q=s.q.toLowerCase(); let items=data.contacts.filter(c=>[fullName(c),companyName(c.companyId),c.role,c.email,c.phone,c.notes].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(c=>companyStatus(c.companyId)===s.status); if(s.priority) items=items.filter(c=>nextFollowUpByContact(c.id)?.priority===s.priority); items.sort((a,b)=>{ const row=c=>({...c, name:fullName(c), company:companyName(c.companyId), status:companyStatus(c.companyId), priority:nextFollowUpByContact(c.id)?.priority || '', nextDue:nextFollowUpByContact(c.id)?.dueDate || '9999-99-99', last:contactLastActivity(c.id)?.updatedAt || c.updatedAt}); return byField(s.sort,s.dir)(row(a),row(b)); }); const extra = `<select data-filter-field="status"><option value="">Alle Status</option>${['Lead','Aktiv','Kunde','Inaktiv'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select data-filter-field="priority"><option value="">Alle Prioritäten</option>${['Hoch','Mittel','Niedrig'].map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select>`; return `${header('Kontakte','Zentrale Arbeitsliste mit Firmen, Prioritäten und Follow-ups.', `<button class="btn primary" data-open-contact>${icon('plus')}Kontakt hinzufügen</button>`)}${toolbar('contacts','Kontakte, Firmen oder Tags suchen ...', extra)}<div class="table-card">${items.length ? contactTable(items) : empty('Keine Kontakte gefunden')}</div>`; }
function companyStatus(id) { return data.companies.find(c=>c.id===id)?.status || '—'; }
function contactTable(items, includeActions=true) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('contacts','name','Name')}</th><th>${sortHead('contacts','company','Firma')}</th><th>${sortHead('contacts','status','Status')}</th><th>${sortHead('contacts','priority','Priorität')}</th><th>${sortHead('contacts','nextDue','Nächstes Follow-up')}</th><th>${sortHead('contacts','last','Letzte Aktivität')}</th>${includeActions?'<th>Aktionen</th>':''}</tr></thead><tbody>${items.map(c=>{ const next=nextFollowUpByContact(c.id); const last=contactLastActivity(c.id); return `<tr class="click-row" data-contact-detail="${c.id}"><td><strong>${escapeHtml(fullName(c))}</strong><div class="kv">${escapeHtml(c.role||'Keine Rolle')}</div></td><td><button class="link-btn" data-company-detail="${c.companyId}">${escapeHtml(companyName(c.companyId))}</button></td><td>${statusBadge(companyStatus(c.companyId))}</td><td>${next ? priorityBadge(next.priority) : '—'}</td><td>${next ? `${escapeHtml(next.title)}<div class="kv">${fmtDate(next.dueDate)}</div>` : '—'}</td><td>${fmtDate(last?.updatedAt || c.updatedAt)}</td>${includeActions?`<td class="actions"><button class="btn" data-edit-contact="${c.id}">${icon('edit')}</button><button class="btn danger" data-delete-contact="${c.id}">${icon('trash')}</button></td>`:''}</tr>`; }).join('')}</tbody></table></div>`; }
function followUpsPage() { const s=tableState.followups; const q=s.q.toLowerCase(); let items=data.followUps.filter(f=>[f.title,f.description,f.type,f.status,f.priority,companyName(f.companyId),contactName(f.contactId)].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(f=>f.status===s.status); if(s.priority) items=items.filter(f=>f.priority===s.priority); if(s.companyId) items=items.filter(f=>f.companyId===s.companyId); if(s.contactId) items=items.filter(f=>f.contactId===s.contactId); if(s.due==='overdue') items=items.filter(isOverdue); if(s.due==='today') items=items.filter(isToday); if(s.due==='week') items=items.filter(isThisWeek); items.sort((a,b)=>{ const row=f=>({...f, company:companyName(f.companyId), contact:contactName(f.contactId), dueDate:f.dueDate || '9999-99-99'}); return byField(s.sort,s.dir)(row(a),row(b)); }); const extra=`<select data-follow-filter="status"><option value="">Alle Status</option><option ${s.status==='Offen'?'selected':''}>Offen</option><option ${s.status==='Erledigt'?'selected':''}>Erledigt</option></select><select data-follow-filter="priority"><option value="">Alle Prioritäten</option>${['Hoch','Mittel','Niedrig'].map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select><select data-follow-filter="companyId"><option value="">Alle Firmen</option>${data.companies.map(c=>`<option value="${c.id}" ${s.companyId===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select><select data-follow-filter="contactId"><option value="">Alle Kontakte</option>${data.contacts.map(c=>`<option value="${c.id}" ${s.contactId===c.id?'selected':''}>${escapeHtml(fullName(c))}</option>`).join('')}</select><select data-follow-filter="due"><option value="">Alle Fälligkeiten</option><option value="overdue" ${s.due==='overdue'?'selected':''}>Überfällig</option><option value="today" ${s.due==='today'?'selected':''}>Heute</option><option value="week" ${s.due==='week'?'selected':''}>Diese Woche</option></select>`; return `${header('Follow-ups','Alle nächsten Schritte in einer sortier- und filterbaren Tabelle.', `<button class="btn primary" data-open-follow>${icon('plus')}Follow-up hinzufügen</button>`)}${toolbar('followups','Follow-ups, Kontakte oder Firmen suchen ...', extra)}<div class="table-card">${items.length ? followUpsTable(items) : empty('Keine Follow-ups gefunden')}</div>`; }
function followUpsTable(items, includeActions=true) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('followups','priority','Priorität')}</th><th>${sortHead('followups','dueDate','Fällig')}</th><th>${sortHead('followups','title','Titel')}</th><th>${sortHead('followups','contact','Kontakt')}</th><th>${sortHead('followups','company','Firma')}</th><th>${sortHead('followups','status','Status')}</th><th>${sortHead('followups','createdAt','Erstellt')}</th>${includeActions?'<th>Aktionen</th>':''}</tr></thead><tbody>${items.map(f=>`<tr><td>${priorityBadge(f.priority)}</td><td>${fmtDate(f.dueDate)}${isOverdue(f)?'<div class="badge overdue">Überfällig</div>':''}</td><td><strong>${escapeHtml(f.title)}</strong><div class="kv">${iconForType(f.type)} ${escapeHtml(f.type || 'Follow-up')}</div></td><td>${f.contactId ? `<button class="link-btn" data-contact-detail="${f.contactId}">${escapeHtml(contactName(f.contactId))}</button>` : '—'}</td><td><button class="link-btn" data-company-detail="${f.companyId}">${escapeHtml(companyName(f.companyId))}</button></td><td>${statusBadge(f.status)}</td><td>${fmtDate(f.createdAt)}</td>${includeActions?`<td class="actions"><button class="btn" data-edit-follow="${f.id}">${icon('edit')}</button>${f.status==='Offen'?`<button class="btn" data-done="${f.id}">Erledigt</button>`:`<button class="btn" data-reopen="${f.id}">Öffnen</button>`}<button class="btn danger" data-delete-follow="${f.id}">${icon('trash')}</button></td>`:''}</tr>`).join('')}</tbody></table></div>`; }
function iconForType(type) { return icon({ 'Anruf':'call', 'E-Mail':'mail', 'Meeting':'meeting', 'Notiz':'note', 'Aufgabe':'task' }[type] || 'followups'); }
function contactDetailPage() { const c=contactById(selectedContactId); if(!c) return empty('Kontakt wurde nicht gefunden'); const fs=contactFollowUps(c.id).sort((a,b)=> tableState.timelineDir==='desc' ? new Date(b.updatedAt)-new Date(a.updatedAt) : new Date(a.updatedAt)-new Date(b.updatedAt)); return `${header(fullName(c),'Kontaktprofil mit Timeline und Follow-ups.', '<button class="btn" data-view="contacts">Zurück</button><button class="btn primary" data-open-follow>'+icon('plus')+'Follow-up hinzufügen</button>')}<section class="detail-grid"><div class="card"><h2>Kontaktdaten</h2><p><button class="link-btn" data-company-detail="${c.companyId}">${escapeHtml(companyName(c.companyId))}</button></p><p><strong>Rolle:</strong> ${escapeHtml(c.role||'—')}</p><p><strong>E-Mail:</strong> ${escapeHtml(c.email||'—')}</p><p><strong>Telefon:</strong> ${escapeHtml(c.phone||'—')}</p><p>${escapeHtml(c.notes || 'Keine Notizen')}</p></div><div class="card wide"><div class="section-head"><h2>Timeline</h2><button class="btn" data-toggle-timeline>Sortierung: ${tableState.timelineDir==='desc'?'Neueste zuerst':'Älteste zuerst'}</button></div>${fs.length ? timeline(fs) : empty('Noch keine Timeline-Einträge')}</div></section>`; }
function timeline(items) { return `<div class="timeline visual">${items.map(f=>`<article class="timeline-item"><span class="timeline-icon">${iconForType(f.type)}</span><div><div class="section-head"><strong>${escapeHtml(f.title)}</strong><span class="kv">${fmtDate(f.updatedAt)}</span></div><p>${escapeHtml(f.description || 'Keine Beschreibung')}</p><div class="actions">${statusBadge(f.status)} ${priorityBadge(f.priority)} <span class="badge">${escapeHtml(f.type || 'Follow-up')}</span><span class="kv">Fällig: ${fmtDate(f.dueDate)}</span></div>${f.completedAt?`<div class="kv">Erledigt am ${fmtDate(f.completedAt)}</div>`:''}</div></article>`).join('')}</div>`; }
function bindActions() {
  document.querySelectorAll('[data-open-company]').forEach(b=>b.onclick=()=>openCompanyForm());
  document.querySelectorAll('[data-edit-company]').forEach(b=>b.onclick=e=>{e.stopPropagation();openCompanyForm(data.companies.find(c=>c.id===b.dataset.editCompany));});
  document.querySelectorAll('[data-delete-company]').forEach(b=>b.onclick=e=>{e.stopPropagation();confirmDelete('Firma löschen?',()=>{data.companies=data.companies.filter(c=>c.id!==b.dataset.deleteCompany);data.contacts=data.contacts.filter(c=>c.companyId!==b.dataset.deleteCompany);data.followUps=data.followUps.filter(f=>f.companyId!==b.dataset.deleteCompany);saveData();});});
  document.querySelectorAll('[data-company-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedCompanyId=b.dataset.companyDetail;selectedContactId=null;view='companyDetail';render();});
  document.querySelectorAll('[data-contact-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedContactId=b.dataset.contactDetail;selectedCompanyId=null;view='contactDetail';render();});
  document.querySelectorAll('[data-open-contact]').forEach(b=>b.onclick=()=>openContactForm()); document.querySelectorAll('[data-edit-contact]').forEach(b=>b.onclick=e=>{e.stopPropagation();openContactForm(data.contacts.find(c=>c.id===b.dataset.editContact));}); document.querySelectorAll('[data-delete-contact]').forEach(b=>b.onclick=e=>{e.stopPropagation();confirmDelete('Kontakt löschen?',()=>{data.contacts=data.contacts.filter(c=>c.id!==b.dataset.deleteContact);data.followUps=data.followUps.map(f=>f.contactId===b.dataset.deleteContact?{...f,contactId:''}:f);saveData();});});
  document.querySelectorAll('[data-open-follow]').forEach(b=>b.onclick=()=>openFollowForm()); document.querySelectorAll('[data-edit-follow]').forEach(b=>b.onclick=()=>openFollowForm(data.followUps.find(f=>f.id===b.dataset.editFollow))); document.querySelectorAll('[data-delete-follow]').forEach(b=>b.onclick=()=>confirmDelete('Follow-up löschen?',()=>{data.followUps=data.followUps.filter(f=>f.id!==b.dataset.deleteFollow);saveData();})); document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.done); f.status='Erledigt'; f.completedAt=isoNow(); f.updatedAt=isoNow(); saveData();}); document.querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.reopen); f.status='Offen'; f.completedAt=''; f.updatedAt=isoNow(); saveData();});
  document.querySelectorAll('[data-table-search]').forEach(i=>i.oninput=e=>{tableState[e.target.dataset.tableSearch].q=e.target.value; render();});
  document.querySelectorAll('[data-sort-kind]').forEach(b=>b.onclick=()=>{const s=tableState[b.dataset.sortKind]; s.dir = s.sort===b.dataset.sortField && s.dir==='asc' ? 'desc' : 'asc'; s.sort=b.dataset.sortField; render();});
  document.querySelectorAll('[data-filter-field]').forEach(s=>s.onchange=e=>{tableState.contacts[e.target.dataset.filterField]=e.target.value; render();});
  document.querySelectorAll('[data-follow-filter]').forEach(s=>s.onchange=e=>{tableState.followups[e.target.dataset.followFilter]=e.target.value; render();});
  $('[data-toggle-timeline]')?.addEventListener('click',()=>{tableState.timelineDir=tableState.timelineDir==='desc'?'asc':'desc';render();});
}
function modal(title, body) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="btn" data-close>Schließen</button></div>${body}</div></div>`); $('[data-close]').onclick=()=>$('.modal-backdrop').remove(); }
function fields(obj, type) { if(type==='company') return `<div class="form-grid"><label class="field">Name*<input name="name" required value="${escapeHtml(obj?.name||'')}"></label><label class="field">Status<select name="status">${['Lead','Aktiv','Kunde','Inaktiv'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Website<input name="website" value="${escapeHtml(obj?.website||'')}"></label><label class="field">Branche<input name="industry" value="${escapeHtml(obj?.industry||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`; if(type==='contact') return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Rolle<input name="role" value="${escapeHtml(obj?.role||'')}"></label><label class="field">Vorname*<input name="firstName" required value="${escapeHtml(obj?.firstName||'')}"></label><label class="field">Nachname*<input name="lastName" required value="${escapeHtml(obj?.lastName||'')}"></label><label class="field">E-Mail<input name="email" type="email" value="${escapeHtml(obj?.email||'')}"></label><label class="field">Telefon<input name="phone" value="${escapeHtml(obj?.phone||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`; return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId||contactById(selectedContactId)?.companyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Kontakt<select name="contactId"><option value="">Kein Kontakt</option>${data.contacts.map(c=>`<option value="${c.id}" ${(obj?.contactId||selectedContactId)===c.id?'selected':''}>${escapeHtml(fullName(c))}</option>`).join('')}</select></label><label class="field">Typ<select name="type">${['Anruf','E-Mail','Meeting','Notiz','Aufgabe'].map(s=>`<option ${obj?.type===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Priorität<select name="priority">${['Niedrig','Mittel','Hoch'].map(s=>`<option ${obj?.priority===s?'selected':''}>${s}</option>`)}</select></label><label class="field full">Titel*<input name="title" required value="${escapeHtml(obj?.title||'')}"></label><label class="field">Fällig am<input name="dueDate" type="date" value="${escapeHtml(obj?.dueDate||'')}"></label><label class="field">Status<select name="status">${['Offen','Erledigt'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field full">Beschreibung<textarea name="description">${escapeHtml(obj?.description||'')}</textarea></label></div>`; }
function handleForm(form, obj, collection, mapper) { const fd=Object.fromEntries(new FormData(form)); if(!form.checkValidity()){form.reportValidity();return;} const now=isoNow(); if(obj) Object.assign(obj, mapper(fd), {updatedAt: now}); else data[collection].push({id:uid(), ...mapper(fd), createdAt:now, updatedAt:now}); $('.modal-backdrop').remove(); saveData(); }
function openCompanyForm(obj) { modal(obj?'Firma bearbeiten':'Firma hinzufügen', `<form id="form">${fields(obj,'company')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'companies',x=>x);}; }
function openContactForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Kontakt bearbeiten':'Kontakt hinzufügen', `<form id="form">${fields(obj,'contact')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'contacts',x=>x);}; }
function openFollowForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Follow-up bearbeiten':'Follow-up hinzufügen', `<form id="form">${fields(obj,'follow')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'followUps',x=>({...x, completedAt:x.status==='Erledigt'?(obj?.completedAt||isoNow()):''}));}; }
function confirmDelete(message, cb) { if (confirm(`${message}\nDiese Aktion kann nicht rückgängig gemacht werden.`)) cb(); }
render();
