const $ = (selector, root = document) => root.querySelector(selector);
const app = document.getElementById('app');
const today = new Date(); today.setHours(0,0,0,0);
const uid = () => crypto.randomUUID();
const isoNow = () => new Date().toISOString();
const toDate = (value) => value ? new Date(`${value}T00:00:00`) : null;
const fmtDate = (value) => value ? new Intl.DateTimeFormat('de-DE').format(new Date(value)) : '—';
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const storeKey = 'simple-crm-data-v1';
let data = loadData();
let view = 'dashboard';
let selectedCompanyId = null;
let selectedContactId = null;
let tableState = { companies: { q:'', sort:'name', dir:'asc' }, contacts: { q:'', status:'', priority:'', sort:'name', dir:'asc' }, followups: { q:'', status:'', priority:'', due:'', sort:'dueDate', dir:'asc' }, products: { q:'', status:'', category:'', sort:'name', dir:'asc' }, sales: { q:'', status:'', productId:'', contactId:'', companyId:'', from:'', to:'', sort:'saleDate', dir:'desc' }, timeline: { q:'', type:'', status:'', priority:'', sort:'date', dir:'desc' } };
const icons = { dashboard:'M3 13h8V3H3v10Zm10 8h8V3h-8v18ZM3 21h8v-6H3v6Z', companies:'M3 21h18M5 21V7l8-4v18M19 21V11l-6-3M9 9h1M9 13h1M9 17h1M15 13h1M15 17h1', contacts:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75', followups:'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2ZM8 14h.01M12 14h.01M16 14h.01', plus:'M12 5v14M5 12h14', search:'m21 21-4.3-4.3M10 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16Z', edit:'M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5Z', trash:'M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15', call:'M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13 1 .36 1.98.7 2.91a2 2 0 0 1-.45 2.11L8.09 10a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.93.34 1.9.57 2.91.7A2 2 0 0 1 22 16.92Z', mail:'M4 4h16v16H4zM22 6l-10 7L2 6', meeting:'M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM23 21v-2a4 4 0 0 0-3-3.87', note:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8M8 17h6', task:'M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11', products:'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16ZM3.3 7 12 12l8.7-5M12 22V12', sales:'M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7H14a3.5 3.5 0 0 1 0 7H6', arrow:'M5 12h14M13 5l7 7-7 7', empty:'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3' };
function icon(name) { return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name] || icons.empty}"/></svg>`; }
function loadData() { const saved = localStorage.getItem(storeKey); if (saved) return JSON.parse(saved); const now = isoNow(); return { companies: [{ id: uid(), name: 'Muster GmbH', website: 'https://beispiel.de', industry: 'Beratung', status: 'Lead', notes: 'Erster Kontakt über Empfehlung.', createdAt: now, updatedAt: now }], contacts: [], followUps: [], products: [], sales: [] }; }
function normalizeData() { data.products ||= []; data.sales ||= []; data.sales.forEach(s => { s.quantity = Math.max(1, Number(s.quantity || 1)); s.unitPrice = Number(s.unitPrice ?? s.price ?? 0); s.totalPrice = Number(s.totalPrice ?? (s.quantity * s.unitPrice)); s.price = s.totalPrice; s.currency ||= 'CHF'; }); }
normalizeData();
function saveData() { normalizeData(); localStorage.setItem(storeKey, JSON.stringify(data)); render(); }
const fullName = c => c ? `${c.firstName || ''} ${c.lastName || ''}`.trim() : '—';
function companyName(id) { return data.companies.find(c => c.id === id)?.name || 'Keine Firma'; }
function contactName(id) { return fullName(data.contacts.find(x => x.id === id)); }
function contactById(id) { return data.contacts.find(c => c.id === id); }
function productById(id) { return data.products.find(p => p.id === id); }
function productName(id) { return productById(id)?.name || '—'; }
function companySales(id) { return data.sales.filter(s => s.companyId === id || contactById(s.contactId)?.companyId === id); }
function contactSales(id) { return data.sales.filter(s => s.contactId === id); }
function formatCurrencyCHF(value) { return `CHF ${new Intl.NumberFormat('de-CH', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value || 0))}`; }
function money(value) { return formatCurrencyCHF(value); }
function saleQuantity(sale) { return Math.max(1, Number(sale?.quantity || 1)); }
function saleUnitPrice(sale) { return Number(sale?.unitPrice ?? sale?.price ?? 0); }
function saleTotal(sale) { return Number(sale?.totalPrice ?? saleQuantity(sale) * saleUnitPrice(sale)); }
function saleCompanyId(sale) { return sale.companyId || contactById(sale.contactId)?.companyId || ''; }
function isOverdue(f) { const d = toDate(f.dueDate); return f.status === 'Offen' && d && d < today; }
function isToday(f) { const d = toDate(f.dueDate); return d && d.getTime() === today.getTime(); }
function isThisWeek(f) { const d = toDate(f.dueDate); if (!d) return false; const end = new Date(today); end.setDate(today.getDate() + 7); return d >= today && d <= end; }
function companyFollowUps(id) { return data.followUps.filter(f => f.companyId === id); }
function contactFollowUps(id) { return data.followUps.filter(f => f.contactId === id); }
function lastActivity(id) { return [...companyFollowUps(id), ...companySales(id)].sort((a,b) => new Date(b.updatedAt || b.saleDate)-new Date(a.updatedAt || a.saleDate))[0]; }
function contactLastActivity(id) { return [...contactFollowUps(id), ...contactSales(id)].sort((a,b) => new Date(b.updatedAt || b.saleDate)-new Date(a.updatedAt || a.saleDate))[0]; }
function nextFollowUpByCompany(id) { return companyFollowUps(id).filter(f => f.status === 'Offen').sort(byField('dueDate','asc'))[0]; }
function nextFollowUpByContact(id) { return contactFollowUps(id).filter(f => f.status === 'Offen').sort(byField('dueDate','asc'))[0]; }
function priorityRank(p) { return { Hoch: 3, Mittel: 2, Niedrig: 1 }[p] || 0; }
function byField(field, dir='asc') { return (a,b) => { const mult = dir === 'desc' ? -1 : 1; let av = field === 'priority' ? priorityRank(a.priority) : (a[field] || ''); let bv = field === 'priority' ? priorityRank(b.priority) : (b[field] || ''); return String(av).localeCompare(String(bv), 'de', { numeric: true }) * mult; }; }
function render(options = {}) { app.innerHTML = `<div class="app-shell"><aside class="sidebar">${brand()}${nav()}</aside><main class="main"><div class="content">${route()}</div></main></div>`; document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => { view = b.dataset.view; selectedCompanyId = null; selectedContactId = null; render(); })); bindActions(); restoreSearchFocus(options.focusSearch); }
function brand() { return `<div class="brand"><span class="brand-mark">${icon('dashboard')}</span><span>Einfaches CRM</span></div>`; }
function nav() { return `<nav class="nav">${[['dashboard','Übersicht','dashboard'],['companies','Firmen','companies'],['contacts','Kontakte','contacts'],['followups','Follow-ups','followups'],['sales','Sales','sales'],['products','Produkte','products']].map(([k,l,i]) => `<button class="${view===k?'active':''}" data-view="${k}">${icon(i)}<span>${l}</span></button>`).join('')}</nav>`; }
function route() { if (view === 'companies') return companiesPage(); if (view === 'contacts') return contactsPage(); if (view === 'followups') return followUpsPage(); if (view === 'sales') return salesPage(); if (view === 'products') return productsPage(); if (view === 'companyDetail') return companyDetailPage(); if (view === 'contactDetail') return contactDetailPage(); return dashboardPage(); }
function header(title, text, action = '') { return `<div class="page-header"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(text)}</p></div><div class="actions">${action}</div></div>`; }
function empty(text) { return `<div class="empty">${icon('empty')}<strong>${escapeHtml(text)}</strong><span>Erstelle neue Einträge oder passe deine Filter an.</span></div>`; }
function statusBadge(status='—') { const cls = ['Erledigt','Gewonnen','Bezahlt','Angenommen'].includes(status) ? 'done' : ['Offen','Angeboten'].includes(status) ? 'open' : status === 'Kunde' ? 'customer' : ['Passiv','Verloren'].includes(status) ? 'inactive' : ''; return `<span class="badge ${cls}">${escapeHtml(status)}</span>`; }
function priorityBadge(p='—') { return `<span class="badge ${p === 'Hoch' ? 'high' : p === 'Mittel' ? 'medium' : ''}">${escapeHtml(p)}</span>`; }
function dashboardPage() { const open = data.followUps.filter(f => f.status === 'Offen').sort(byField('dueDate')); const overdue = open.filter(isOverdue).length; return `${header('Übersicht','Fokus auf aktuelle Firmen, Kontakte und nächste Schritte.', `<button class="btn primary" data-open-follow>${icon('plus')}Follow-up hinzufügen</button>`)}<section class="grid four">${[['Firmen',data.companies.length,'companies'],['Kontakte',data.contacts.length,'contacts'],['Sales',data.sales.length,'sales'],['Produkte',data.products.length,'products']].map(s=>`<button class="card stat" data-view="${s[2]}">${icon(s[2])}<span class="kv">${s[0]}</span><strong>${s[1]}</strong></button>`).join('')}</section><section class="card" style="margin-top:18px"><h2>Nächste Follow-ups</h2>${open.length ? followUpsTable(open.slice(0,8), false) : empty('Keine offenen Follow-ups')}</section>`; }
function toolbar(kind, placeholder, extra='') { const s=tableState[kind]; return `<div class="filters"><label class="search-field">${icon('search')}<input data-table-search="${kind}" placeholder="${placeholder}" value="${escapeHtml(s.q)}"></label>${extra}</div>`; }
function sortHead(kind, field, label) { const s=tableState[kind]; return `<button class="sort-head ${s.sort===field?'active':''}" data-sort-kind="${kind}" data-sort-field="${field}">${label}${s.sort===field ? (s.dir==='asc'?' ↑':' ↓') : ''}</button>`; }
function companiesPage() { const s=tableState.companies; const q=s.q.toLowerCase(); const items=data.companies.filter(c=>[c.name,c.status,c.industry,c.website].join(' ').toLowerCase().includes(q)).sort((a,b)=>{ const row = c => ({...c, contacts:data.contacts.filter(x=>x.companyId===c.id).length, nextDue:nextFollowUpByCompany(c.id)?.dueDate || '9999-99-99', last:lastActivity(c.id)?.updatedAt || c.updatedAt}); return byField(s.sort,s.dir)(row(a),row(b)); }); return `${header('Firmen','Alle Organisationen als klare Tabelle.', `<button class="btn primary" data-open-company>${icon('plus')}Firma hinzufügen</button>`)}${toolbar('companies','Firmen suchen ...')}<div class="table-card">${items.length ? companyTable(items) : empty('Keine Firmen gefunden')}</div>`; }
function companyTable(items) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('companies','name','Firma')}</th><th>${sortHead('companies','status','Status')}</th><th>${sortHead('companies','industry','Branche')}</th><th>${sortHead('companies','last','Letzte Aktivität')}</th><th>${sortHead('companies','nextDue','Nächster Follow-up')}</th><th>${sortHead('companies','contacts','Kontakte')}</th><th>Aktionen</th></tr></thead><tbody>${items.map(c => { const next=nextFollowUpByCompany(c.id), last=lastActivity(c.id); return `<tr class="click-row" data-company-detail="${c.id}"><td><strong>${escapeHtml(c.name)}</strong><div class="kv">${escapeHtml(c.website || 'Keine Website')}</div></td><td>${statusBadge(c.status)}</td><td>${escapeHtml(c.industry || '—')}</td><td>${fmtDate(last?.updatedAt || c.updatedAt)}</td><td>${next ? `${escapeHtml(next.title)}<div class="kv">${fmtDate(next.dueDate)}</div>` : '—'}</td><td>${data.contacts.filter(x=>x.companyId===c.id).length}</td><td class="actions"><button class="btn" data-edit-company="${c.id}">${icon('edit')}</button><button class="btn danger" data-delete-company="${c.id}">${icon('trash')}</button></td></tr>`; }).join('')}</tbody></table></div>`; }
function companyDetailPage() { const c=data.companies.find(x=>x.id===selectedCompanyId); if(!c) return empty('Firma wurde nicht gefunden'); const contacts=data.contacts.filter(x=>x.companyId===c.id); const sales=companySales(c.id); const openF=contacts.flatMap(x=>contactFollowUps(x.id)).filter(f=>f.status==='Offen').sort(byField('dueDate','asc')); const revenue=sales.reduce((sum,x)=>sum+saleTotal(x),0); return `${header(c.name,'Firmendetails, Kontakte und Umsatz im Überblick.', '<button class="btn" data-view="companies">Zurück</button><button class="btn primary" data-open-contact>'+icon('plus')+'Kontakt hinzufügen</button>')}<section class="grid four" style="margin-bottom:18px"><div class="card stat">${icon('sales')}<span class="kv">Gesamtumsatz</span><strong>${money(revenue)}</strong></div><div class="card stat">${icon('contacts')}<span class="kv">Kontakte</span><strong>${contacts.length}</strong></div><div class="card stat">${icon('followups')}<span class="kv">Offene Follow-ups</span><strong>${openF.length}</strong></div><div class="card stat">${icon('dashboard')}<span class="kv">Letzte Aktivität</span><strong>${fmtDate(lastActivity(c.id)?.updatedAt || lastActivity(c.id)?.saleDate || c.updatedAt)}</strong></div></section><section class="detail-grid"><div class="card"><h2>Profil</h2><p>${statusBadge(c.status)}</p><p><strong>Website:</strong> ${c.website ? `<a href="${escapeHtml(c.website)}" target="_blank">${escapeHtml(c.website)}</a>` : '—'}</p><p><strong>Branche:</strong> ${escapeHtml(c.industry || '—')}</p><p>${escapeHtml(c.notes || 'Keine Notizen')}</p></div><div class="card wide"><h2>Kontakte</h2>${contacts.length ? contactTable(contacts, false) : empty('Noch keine Kontakte vorhanden')}</div><div class="card wide"><h2>Sales dieser Firma</h2>${sales.length ? salesTable(sales, false) : empty('Noch keine Sales vorhanden')}</div><div class="card wide"><h2>Nächste offene Follow-ups</h2>${openF.length ? followUpsTable(openF.slice(0,6), false) : empty('Keine offenen Follow-ups')}</div></section>`; }
function contactsPage() { const s=tableState.contacts; const q=s.q.toLowerCase(); let items=data.contacts.filter(c=>[fullName(c),companyName(c.companyId),c.role,c.email,c.phone,c.notes].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(c=>companyStatus(c.companyId)===s.status); if(s.priority) items=items.filter(c=>nextFollowUpByContact(c.id)?.priority===s.priority); items.sort((a,b)=>{ const row=c=>({...c, name:fullName(c), company:companyName(c.companyId), status:companyStatus(c.companyId), priority:nextFollowUpByContact(c.id)?.priority || '', nextDue:nextFollowUpByContact(c.id)?.dueDate || '9999-99-99', last:contactLastActivity(c.id)?.updatedAt || c.updatedAt}); return byField(s.sort,s.dir)(row(a),row(b)); }); const extra = `<select data-filter-field="status"><option value="">Alle Status</option>${['Lead','Kunde','Passiv'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select data-filter-field="priority"><option value="">Alle Prioritäten</option>${['Hoch','Mittel','Niedrig'].map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select>`; return `${header('Kontakte','Zentrale Arbeitsliste mit Firmen, Prioritäten und Follow-ups.', `<button class="btn primary" data-open-contact>${icon('plus')}Kontakt hinzufügen</button>`)}${toolbar('contacts','Kontakte, Firmen oder Tags suchen ...', extra)}<div class="table-card">${items.length ? contactTable(items) : empty('Keine Kontakte gefunden')}</div>`; }
function companyStatus(id) { return data.companies.find(c=>c.id===id)?.status || '—'; }
function contactTable(items, includeActions=true) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('contacts','name','Name')}</th><th>${sortHead('contacts','company','Firma')}</th><th>${sortHead('contacts','status','Status')}</th><th>${sortHead('contacts','priority','Priorität')}</th><th>${sortHead('contacts','nextDue','Nächstes Follow-up')}</th><th>${sortHead('contacts','last','Letzte Aktivität')}</th>${includeActions?'<th>Aktionen</th>':''}</tr></thead><tbody>${items.map(c=>{ const next=nextFollowUpByContact(c.id); const last=contactLastActivity(c.id); return `<tr class="click-row" data-contact-detail="${c.id}"><td><strong>${escapeHtml(fullName(c))}</strong><div class="kv">${escapeHtml(c.role||'Keine Rolle')}</div></td><td><button class="link-btn" data-company-detail="${c.companyId}">${escapeHtml(companyName(c.companyId))}</button></td><td>${statusBadge(companyStatus(c.companyId))}</td><td>${next ? priorityBadge(next.priority) : '—'}</td><td>${next ? `${escapeHtml(next.title)}<div class="kv">${fmtDate(next.dueDate)}</div>` : '—'}</td><td>${fmtDate(last?.updatedAt || c.updatedAt)}</td>${includeActions?`<td class="actions"><button class="btn" data-edit-contact="${c.id}">${icon('edit')}</button><button class="btn danger" data-delete-contact="${c.id}">${icon('trash')}</button></td>`:''}</tr>`; }).join('')}</tbody></table></div>`; }
function followUpsPage() { const s=tableState.followups; const q=s.q.toLowerCase(); let items=data.followUps.filter(f=>[f.title,f.description,f.type,f.status,f.priority,companyName(f.companyId),contactName(f.contactId)].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(f=>f.status===s.status); if(s.priority) items=items.filter(f=>f.priority===s.priority); if(s.due==='overdue') items=items.filter(isOverdue); if(s.due==='today') items=items.filter(isToday); if(s.due==='week') items=items.filter(isThisWeek); items.sort((a,b)=>{ const row=f=>({...f, company:companyName(f.companyId), contact:contactName(f.contactId), dueDate:f.dueDate || '9999-99-99'}); return byField(s.sort,s.dir)(row(a),row(b)); }); const extra=`<select data-follow-filter="status"><option value="">Alle Status</option><option ${s.status==='Offen'?'selected':''}>Offen</option><option ${s.status==='Erledigt'?'selected':''}>Erledigt</option></select><select data-follow-filter="priority"><option value="">Alle Prioritäten</option>${['Hoch','Mittel','Niedrig'].map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select><select data-follow-filter="due"><option value="">Alle Fälligkeiten</option><option value="overdue" ${s.due==='overdue'?'selected':''}>Überfällig</option><option value="today" ${s.due==='today'?'selected':''}>Heute</option><option value="week" ${s.due==='week'?'selected':''}>Diese Woche</option></select>`; return `${header('Follow-ups','Alle nächsten Schritte in einer sortier- und filterbaren Tabelle.', `<button class="btn primary" data-open-follow>${icon('plus')}Follow-up hinzufügen</button>`)}${toolbar('followups','Follow-ups, Kontakte oder Firmen suchen ...', extra)}<div class="table-card">${items.length ? followUpsTable(items) : empty('Keine Follow-ups gefunden')}</div>`; }
function followUpsTable(items, includeActions=true) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('followups','priority','Priorität')}</th><th>${sortHead('followups','dueDate','Fällig')}</th><th>${sortHead('followups','type','Typ')}</th><th>${sortHead('followups','contact','Kontakt')}</th><th>${sortHead('followups','company','Firma')}</th><th>${sortHead('followups','status','Status')}</th><th>${sortHead('followups','createdAt','Erstellt')}</th>${includeActions?'<th>Aktionen</th>':''}</tr></thead><tbody>${items.map(f=>`<tr><td>${priorityBadge(f.priority)}</td><td>${fmtDate(f.dueDate)}${isOverdue(f)?'<div class="badge overdue">Überfällig</div>':''}</td><td><span class="followup-type-icon" title="${escapeHtml(f.type || 'Follow-up')}" aria-label="${escapeHtml(f.type || 'Follow-up')}">${iconForType(f.type)}</span></td><td>${f.contactId ? `<button class="link-btn" data-contact-detail="${f.contactId}">${escapeHtml(contactName(f.contactId))}</button>` : '—'}</td><td><button class="link-btn" data-company-detail="${f.companyId}">${escapeHtml(companyName(f.companyId))}</button></td><td>${statusBadge(f.status)}</td><td>${fmtDate(f.createdAt)}</td>${includeActions?`<td class="actions"><button class="btn" data-edit-follow="${f.id}">${icon('edit')}</button>${f.status==='Offen'?`<button class="btn" data-done="${f.id}">Erledigt</button>`:`<button class="btn" data-reopen="${f.id}">Öffnen</button>`}<button class="btn danger" data-delete-follow="${f.id}">${icon('trash')}</button></td>`:''}</tr>`).join('')}</tbody></table></div>`; }
function iconForType(type) { return icon({ 'Anruf':'call', 'E-Mail':'mail', 'Meeting':'meeting', 'Notiz':'note', 'Aufgabe':'task' }[type] || 'followups'); }
function contactDetailPage() { const c=contactById(selectedContactId); if(!c) return empty('Kontakt wurde nicht gefunden'); const ti=contactTimelineItems(c.id); return `${header(fullName(c),'Timeline aller Follow-ups und Sales.', '<button class="btn" data-view="contacts">Zurück</button><button class="btn" data-show-contact>'+icon('contacts')+'Kontaktdaten anzeigen</button><button class="btn primary" data-open-follow>'+icon('plus')+'Follow-up hinzufügen</button><button class="btn primary" data-open-sale>'+icon('plus')+'Sale hinzufügen</button>')}<section class="card wide"><div class="section-head"><h2>Timeline-Tabelle</h2><span class="kv">Neueste Ereignisse zuerst</span></div>${timelineToolbar()}${ti.length ? timelineTable(ti) : empty('Noch keine Timeline-Einträge')}</section>`; }
function timelineToolbar() { const s=tableState.timeline; return toolbar('timeline','Timeline durchsuchen ...', `<select data-timeline-filter="type"><option value="">Alle Typen</option><option value="follow" ${s.type==='follow'?'selected':''}>Follow-ups</option><option value="sale" ${s.type==='sale'?'selected':''}>Sales</option></select><select data-timeline-filter="status"><option value="">Alle Status</option>${['Offen','Erledigt','Angeboten','Angenommen','Gewonnen','Verloren','Bezahlt'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select data-timeline-filter="priority"><option value="">Alle Prioritäten</option>${['Hoch','Mittel','Niedrig'].map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select>`); }
function timelineRows(contactId) { return contactTimelineItems(contactId).map(e=>{ if(e.kind==='sale'){ const x=e.item; return { kind:'sale', date:x.saleDate||x.updatedAt, type:'Sale', title:productName(x.productId), details:[x.description,x.notes].filter(Boolean).join(' · ') || 'Gekauftes Produkt', status:x.status, priority:'—', product:productName(x.productId), quantity:saleQuantity(x), amount:saleTotal(x), dueDate:'', responsible:'—', item:x }; } const f=e.item; return { kind:'follow', date:f.completedAt||f.dueDate||f.updatedAt, type:f.type||'Follow-up', title:f.title, details:f.description||'Keine Beschreibung', status:f.status, priority:f.priority, product:'—', quantity:'—', amount:'', dueDate:f.dueDate, responsible:contactName(f.contactId), item:f }; }); }
function contactTimelineItems(contactId) { const s=tableState.timeline; let rows=timelineRowsRaw(contactId); const q=s.q.toLowerCase(); if(q) rows=rows.filter(r=>[r.type,r.title,r.details,r.status,r.priority,r.product,r.responsible].join(' ').toLowerCase().includes(q)); if(s.type) rows=rows.filter(r=>r.kind===s.type); if(s.status) rows=rows.filter(r=>r.status===s.status); if(s.priority) rows=rows.filter(r=>r.priority===s.priority); return rows.sort((a,b)=>byField(s.sort,s.dir)(a,b)); }
function timelineRowsRaw(contactId) { const fs=contactFollowUps(contactId).map(f=>({kind:'follow', date:f.completedAt||f.dueDate||f.updatedAt, type:f.type||'Follow-up', title:f.title, details:f.description||'Keine Beschreibung', status:f.status, priority:f.priority, product:'—', quantity:'—', amount:'', dueDate:f.dueDate, responsible:contactName(f.contactId), item:f})); const ss=contactSales(contactId).map(x=>({kind:'sale', date:x.saleDate||x.updatedAt, type:'Sale', title:productName(x.productId), details:[x.description,x.notes].filter(Boolean).join(' · ') || 'Gekauftes Produkt', status:x.status, priority:'—', product:productName(x.productId), quantity:saleQuantity(x), amount:saleTotal(x), dueDate:'', responsible:contactName(x.contactId), item:x})); return [...fs,...ss]; }
function timelineTable(items) { return `<div class="table-wrap timeline-table"><table><thead><tr><th>${sortHead('timeline','date','Datum')}</th><th>${sortHead('timeline','type','Typ')}</th><th>${sortHead('timeline','status','Status')}</th><th>${sortHead('timeline','priority','Priorität')}</th><th>Produkt</th><th>Menge</th><th>${sortHead('timeline','amount','Betrag')}</th><th>${sortHead('timeline','dueDate','Fälligkeit')}</th><th>Verantwortlich</th><th>Aktionen</th></tr></thead><tbody>${items.map(r=>`<tr><td>${fmtDate(r.date)}</td><td><span class="event-type" title="${escapeHtml(r.type)}" aria-label="${escapeHtml(r.type)}">${r.kind==='sale'?icon('sales'):iconForType(r.type)}</span></td><td>${statusBadge(r.status)}</td><td>${r.priority&&r.priority!=='—'?priorityBadge(r.priority):'—'}</td><td>${r.product&&r.product!=='—'?`<span class="badge product">${escapeHtml(r.product)}</span>`:'—'}</td><td>${escapeHtml(r.quantity)}</td><td>${r.amount!==''?`<strong>${money(r.amount)}</strong>`:'—'}</td><td>${fmtDate(r.dueDate)}</td><td>${escapeHtml(r.responsible||'—')}</td><td class="actions"><button class="btn danger" ${r.kind==='sale'?`data-delete-sale="${r.item.id}"`:`data-delete-follow="${r.item.id}"`}>${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div>`; }
function timeline(items) { return timelineTable(items); }

function productsPage() { const s=tableState.products; const q=s.q.toLowerCase(); let items=data.products.filter(p=>[p.name,p.description,p.category,p.status].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(p=>p.status===s.status); if(s.category) items=items.filter(p=>p.category===s.category); items.sort(byField(s.sort,s.dir)); const cats=[...new Set(data.products.map(p=>p.category).filter(Boolean))]; const extra=`<select data-product-filter="status"><option value="">Alle Status</option>${['Aktiv','Inaktiv'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select data-product-filter="category"><option value="">Alle Kategorien</option>${cats.map(x=>`<option ${s.category===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select>`; return `${header('Produkte','Produktkatalog mit Preisen, Status und Kategorien.', `<button class="btn primary" data-open-product>${icon('plus')}Produkt hinzufügen</button>`)}${toolbar('products','Produkte suchen ...', extra)}<div class="table-card">${items.length ? productTable(items) : empty('Keine Produkte gefunden')}</div>`; }
function productTable(items) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('products','name','Produkt')}</th><th>${sortHead('products','category','Kategorie')}</th><th>${sortHead('products','price','Preis')}</th><th>${sortHead('products','status','Status')}</th><th>${sortHead('products','createdAt','Erstellt')}</th><th>${sortHead('products','updatedAt','Aktualisiert')}</th><th>Aktionen</th></tr></thead><tbody>${items.map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong><div class="kv">${escapeHtml(p.description || 'Keine Beschreibung')}</div></td><td>${p.category ? `<span class="badge product">${escapeHtml(p.category)}</span>` : '—'}</td><td><strong>${money(p.price)}</strong></td><td>${statusBadge(p.status)}</td><td>${fmtDate(p.createdAt)}</td><td>${fmtDate(p.updatedAt)}</td><td class="actions"><button class="btn" data-edit-product="${p.id}">${icon('edit')}</button><button class="btn danger" data-delete-product="${p.id}">${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div>`; }
function salesPage() { const s=tableState.sales; const q=s.q.toLowerCase(); let items=data.sales.filter(x=>[x.description,x.notes,x.status,contactName(x.contactId),companyName(saleCompanyId(x)),productName(x.productId)].join(' ').toLowerCase().includes(q)); if(s.status) items=items.filter(x=>x.status===s.status); if(s.productId) items=items.filter(x=>x.productId===s.productId); if(s.contactId) items=items.filter(x=>x.contactId===s.contactId); if(s.companyId) items=items.filter(x=>saleCompanyId(x)===s.companyId); if(s.from) items=items.filter(x=>(x.saleDate||'')>=s.from); if(s.to) items=items.filter(x=>(x.saleDate||'')<=s.to); items.sort((a,b)=>{ const row=x=>({...x, contact:contactName(x.contactId), company:companyName(saleCompanyId(x)), product:productName(x.productId), quantity:saleQuantity(x), unitPrice:saleUnitPrice(x), totalPrice:saleTotal(x), saleDate:x.saleDate||'9999-99-99'}); return byField(s.sort,s.dir)(row(a),row(b)); }); const extra=`<select data-sale-filter="status"><option value="">Alle Status</option>${['Angeboten','Angenommen','Gewonnen','Verloren','Bezahlt'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select data-sale-filter="productId"><option value="">Alle Produkte</option>${data.products.map(p=>`<option value="${p.id}" ${s.productId===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select><input type="date" data-sale-filter="from" value="${escapeHtml(s.from)}"><input type="date" data-sale-filter="to" value="${escapeHtml(s.to)}">`; return `${header('Sales','Erfasste Verkäufe mit Kontakt, Firma, Produkt und Umsatz.', `<button class="btn primary" data-open-sale>${icon('plus')}Sale hinzufügen</button>`)}${toolbar('sales','Sales, Produkte, Kontakte oder Firmen suchen ...', extra)}<div class="table-card">${items.length ? salesTable(items) : empty('Keine Sales gefunden')}</div>`; }
function salesTable(items, includeActions=true) { return `<div class="table-wrap"><table><thead><tr><th>${sortHead('sales','saleDate','Datum')}</th><th>${sortHead('sales','contact','Kontakt')}</th><th>${sortHead('sales','company','Firma')}</th><th>${sortHead('sales','product','Produkt')}</th><th>${sortHead('sales','quantity','Menge')}</th><th>${sortHead('sales','unitPrice','Einzelpreis')}</th><th>${sortHead('sales','totalPrice','Gesamtpreis')}</th><th>${sortHead('sales','status','Status')}</th><th>Notizen / Beschreibung</th>${includeActions?'<th>Aktionen</th>':''}</tr></thead><tbody>${items.map(x=>`<tr><td>${fmtDate(x.saleDate)}</td><td><button class="link-btn" data-contact-detail="${x.contactId}">${escapeHtml(contactName(x.contactId))}</button></td><td><button class="link-btn" data-company-detail="${saleCompanyId(x)}">${escapeHtml(companyName(saleCompanyId(x)))}</button></td><td><span class="badge product">${escapeHtml(productName(x.productId))}</span><div class="kv">${escapeHtml(x.description || '')}</div></td><td>${saleQuantity(x)}</td><td>${money(saleUnitPrice(x))}</td><td><strong>${money(saleTotal(x))}</strong></td><td>${statusBadge(x.status)}</td><td><span class="truncate" title="${escapeHtml([x.description,x.notes].filter(Boolean).join(' · '))}">${escapeHtml([x.description,x.notes].filter(Boolean).join(' · ')||'—')}</span></td>${includeActions?`<td class="actions"><button class="btn" data-edit-sale="${x.id}">${icon('edit')}</button><button class="btn danger" data-delete-sale="${x.id}">${icon('trash')}</button></td>`:''}</tr>`).join('')}</tbody></table></div>`; }

function openContactDetails(c) { if(!c) return; modal(`Kontaktdaten: ${escapeHtml(fullName(c))}`, `<div class="contact-modal"><div class="contact-hero">${icon('contacts')}<div><h3>${escapeHtml(fullName(c))}</h3><p>${escapeHtml(c.role||'Keine Rolle')} · ${escapeHtml(companyName(c.companyId))}</p></div></div><div class="detail-list"><div>${icon('companies')}<span>Firma</span><strong>${escapeHtml(companyName(c.companyId))}</strong></div><div>${icon('mail')}<span>E-Mail</span><strong>${escapeHtml(c.email||'—')}</strong></div><div>${icon('call')}<span>Telefon</span><strong>${escapeHtml(c.phone||'—')}</strong></div><div>${icon('dashboard')}<span>Status</span><strong>${statusBadge(companyStatus(c.companyId))}</strong></div><div>${icon('note')}<span>Tags / Kategorie</span><strong>${escapeHtml(c.role||'—')}</strong></div><div class="wide">${icon('note')}<span>Notizen</span><strong>${escapeHtml(c.notes||'Keine Notizen')}</strong></div><div>${icon('plus')}<span>Erstellt</span><strong>${fmtDate(c.createdAt)}</strong></div><div>${icon('edit')}<span>Aktualisiert</span><strong>${fmtDate(c.updatedAt)}</strong></div></div></div>`); }

function restoreSearchFocus(focusSearch) {
  if (!focusSearch) return;
  const input = $(`[data-table-search="${focusSearch.kind}"]`);
  if (!input) return;
  input.focus();
  const cursor = Math.min(focusSearch.cursor ?? input.value.length, input.value.length);
  input.setSelectionRange(cursor, cursor);
}
function bindActions() {
  document.querySelectorAll('[data-open-company]').forEach(b=>b.onclick=()=>openCompanyForm());
  document.querySelectorAll('[data-edit-company]').forEach(b=>b.onclick=e=>{e.stopPropagation();openCompanyForm(data.companies.find(c=>c.id===b.dataset.editCompany));});
  document.querySelectorAll('[data-delete-company]').forEach(b=>b.onclick=e=>{e.stopPropagation();confirmDelete('Firma löschen?',()=>{data.companies=data.companies.filter(c=>c.id!==b.dataset.deleteCompany);data.contacts=data.contacts.filter(c=>c.companyId!==b.dataset.deleteCompany);data.followUps=data.followUps.filter(f=>f.companyId!==b.dataset.deleteCompany);data.sales=data.sales.filter(x=>saleCompanyId(x)!==b.dataset.deleteCompany);saveData();});});
  document.querySelectorAll('[data-company-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedCompanyId=b.dataset.companyDetail;selectedContactId=null;view='companyDetail';render();});
  document.querySelectorAll('[data-contact-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedContactId=b.dataset.contactDetail;selectedCompanyId=null;view='contactDetail';render();});
  document.querySelectorAll('[data-show-contact]').forEach(b=>b.onclick=()=>openContactDetails(contactById(selectedContactId)));
  document.querySelectorAll('[data-open-contact]').forEach(b=>b.onclick=()=>openContactForm()); document.querySelectorAll('[data-edit-contact]').forEach(b=>b.onclick=e=>{e.stopPropagation();openContactForm(data.contacts.find(c=>c.id===b.dataset.editContact));}); document.querySelectorAll('[data-delete-contact]').forEach(b=>b.onclick=e=>{e.stopPropagation();confirmDelete('Kontakt löschen?',()=>{data.contacts=data.contacts.filter(c=>c.id!==b.dataset.deleteContact);data.followUps=data.followUps.map(f=>f.contactId===b.dataset.deleteContact?{...f,contactId:''}:f);data.sales=data.sales.filter(x=>x.contactId!==b.dataset.deleteContact);saveData();});});
  document.querySelectorAll('[data-open-product]').forEach(b=>b.onclick=()=>openProductForm()); document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProductForm(data.products.find(p=>p.id===b.dataset.editProduct))); document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>confirmDelete('Produkt löschen?',()=>{data.products=data.products.filter(p=>p.id!==b.dataset.deleteProduct);data.sales=data.sales.map(x=>x.productId===b.dataset.deleteProduct?{...x,productId:''}:x);saveData();}));
  document.querySelectorAll('[data-open-sale]').forEach(b=>b.onclick=()=>openSaleForm()); document.querySelectorAll('[data-edit-sale]').forEach(b=>b.onclick=()=>openSaleForm(data.sales.find(x=>x.id===b.dataset.editSale))); document.querySelectorAll('[data-delete-sale]').forEach(b=>b.onclick=()=>confirmDelete('Sale löschen?',()=>{data.sales=data.sales.filter(x=>x.id!==b.dataset.deleteSale);saveData();}));
  document.querySelectorAll('[data-open-follow]').forEach(b=>b.onclick=()=>openFollowForm()); document.querySelectorAll('[data-edit-follow]').forEach(b=>b.onclick=()=>openFollowForm(data.followUps.find(f=>f.id===b.dataset.editFollow))); document.querySelectorAll('[data-delete-follow]').forEach(b=>b.onclick=()=>confirmDelete('Follow-up löschen?',()=>{data.followUps=data.followUps.filter(f=>f.id!==b.dataset.deleteFollow);saveData();})); document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.done); f.status='Erledigt'; f.completedAt=isoNow(); f.updatedAt=isoNow(); saveData();}); document.querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>{const f=data.followUps.find(x=>x.id===b.dataset.reopen); f.status='Offen'; f.completedAt=''; f.updatedAt=isoNow(); saveData();});
  document.querySelectorAll('[data-table-search]').forEach(i=>i.oninput=e=>{const kind=e.target.dataset.tableSearch; const cursor=e.target.selectionStart; tableState[kind].q=e.target.value; render({ focusSearch: { kind, cursor } });});
  document.querySelectorAll('[data-sort-kind]').forEach(b=>b.onclick=()=>{const s=tableState[b.dataset.sortKind]; s.dir = s.sort===b.dataset.sortField && s.dir==='asc' ? 'desc' : 'asc'; s.sort=b.dataset.sortField; render();});
  document.querySelectorAll('[data-filter-field]').forEach(s=>s.onchange=e=>{tableState.contacts[e.target.dataset.filterField]=e.target.value; render();});
  document.querySelectorAll('[data-follow-filter]').forEach(s=>s.onchange=e=>{tableState.followups[e.target.dataset.followFilter]=e.target.value; render();});
  document.querySelectorAll('[data-product-filter]').forEach(s=>s.onchange=e=>{tableState.products[e.target.dataset.productFilter]=e.target.value; render();});
  document.querySelectorAll('[data-sale-filter]').forEach(s=>s.onchange=e=>{tableState.sales[e.target.dataset.saleFilter]=e.target.value; render();});
  document.querySelectorAll('[data-timeline-filter]').forEach(s=>s.onchange=e=>{tableState.timeline[e.target.dataset.timelineFilter]=e.target.value; render();});
}
function modal(title, body) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="btn" data-close>Schließen</button></div>${body}</div></div>`); $('[data-close]').onclick=()=>$('.modal-backdrop').remove(); }
function fields(obj, type) {
  if(type==='company') return `<div class="form-grid"><label class="field">Name*<input name="name" required value="${escapeHtml(obj?.name||'')}"></label><label class="field">Status<select name="status">${['Lead','Kunde','Passiv'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Website<input name="website" value="${escapeHtml(obj?.website||'')}"></label><label class="field">Branche<input name="industry" value="${escapeHtml(obj?.industry||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`;
  if(type==='contact') return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Rolle<input name="role" value="${escapeHtml(obj?.role||'')}"></label><label class="field">Vorname*<input name="firstName" required value="${escapeHtml(obj?.firstName||'')}"></label><label class="field">Nachname*<input name="lastName" required value="${escapeHtml(obj?.lastName||'')}"></label><label class="field">E-Mail<input name="email" type="email" value="${escapeHtml(obj?.email||'')}"></label><label class="field">Telefon<input name="phone" value="${escapeHtml(obj?.phone||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`;
  if(type==='product') return `<div class="form-grid"><label class="field full">Name*<input name="name" required value="${escapeHtml(obj?.name||'')}"></label><label class="field full">Beschreibung<textarea name="description">${escapeHtml(obj?.description||'')}</textarea></label><label class="field">Preis*<input name="price" type="number" step="0.01" min="0" required value="${escapeHtml(obj?.price||'')}"></label><label class="field">Kategorie<input name="category" value="${escapeHtml(obj?.category||'')}"></label><label class="field">Status<select name="status">${['Aktiv','Inaktiv'].map(x=>`<option ${obj?.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div>`;
  if(type==='sale') { const quantity=saleQuantity(obj); const unit=saleUnitPrice(obj)||productById(obj?.productId)?.price||data.products[0]?.price||0; return `<div class="form-grid"><label class="field">Kontakt*<select name="contactId" required>${data.contacts.map(c=>`<option value="${c.id}" ${(obj?.contactId||selectedContactId)===c.id?'selected':''}>${escapeHtml(fullName(c))} · ${escapeHtml(companyName(c.companyId))}</option>`).join('')}</select></label><label class="field">Produkt*<select name="productId" required data-product-select>${data.products.map(p=>`<option value="${p.id}" data-price="${escapeHtml(p.price)}" ${(obj?.productId)===p.id?'selected':''}>${escapeHtml(p.name)} · ${money(p.price)}</option>`).join('')}</select></label><label class="field">Menge*<input name="quantity" data-sale-quantity type="number" step="1" min="1" required value="${escapeHtml(quantity)}"></label><label class="field">Einzelpreis CHF*<input name="unitPrice" data-sale-unit-price type="number" step="0.01" min="0" required value="${escapeHtml(unit)}"></label><label class="field">Gesamtpreis<input name="totalPriceDisplay" data-sale-total readonly value="${escapeHtml(money(quantity*unit))}"></label><label class="field">Status<select name="status">${['Angeboten','Angenommen','Gewonnen','Verloren','Bezahlt'].map(x=>`<option ${obj?.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Verkaufsdatum*<input name="saleDate" type="date" required value="${escapeHtml(obj?.saleDate||new Date().toISOString().slice(0,10))}"></label><label class="field full">Beschreibung<input name="description" value="${escapeHtml(obj?.description||'')}"></label><label class="field full">Notizen<textarea name="notes">${escapeHtml(obj?.notes||'')}</textarea></label></div>`; }
  return `<div class="form-grid"><label class="field">Firma*<select name="companyId" required>${data.companies.map(c=>`<option value="${c.id}" ${(obj?.companyId||selectedCompanyId||contactById(selectedContactId)?.companyId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="field">Kontakt<select name="contactId"><option value="">Kein Kontakt</option>${data.contacts.map(c=>`<option value="${c.id}" ${(obj?.contactId||selectedContactId)===c.id?'selected':''}>${escapeHtml(fullName(c))}</option>`).join('')}</select></label><label class="field">Typ<select name="type">${['Anruf','E-Mail','Meeting','Notiz','Aufgabe'].map(s=>`<option ${obj?.type===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Priorität<select name="priority">${['Niedrig','Mittel','Hoch'].map(s=>`<option ${obj?.priority===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Fällig am<input name="dueDate" type="date" value="${escapeHtml(obj?.dueDate||'')}"></label><label class="field">Status<select name="status">${['Offen','Erledigt'].map(s=>`<option ${obj?.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field full">Beschreibung<textarea name="description">${escapeHtml(obj?.description||'')}</textarea></label></div>`;
}
function handleForm(form, obj, collection, mapper) { const fd=Object.fromEntries(new FormData(form)); if(!form.checkValidity()){form.reportValidity();return;} const now=isoNow(); if(obj) Object.assign(obj, mapper(fd), {updatedAt: now}); else data[collection].push({id:uid(), ...mapper(fd), createdAt:now, updatedAt:now}); $('.modal-backdrop').remove(); saveData(); }
function openCompanyForm(obj) { modal(obj?'Firma bearbeiten':'Firma hinzufügen', `<form id="form">${fields(obj,'company')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'companies',x=>x);}; }
function openContactForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Kontakt bearbeiten':'Kontakt hinzufügen', `<form id="form">${fields(obj,'contact')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'contacts',x=>x);}; }
function openProductForm(obj) { modal(obj?'Produkt bearbeiten':'Produkt hinzufügen', `<form id="form">${fields(obj,'product')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'products',x=>({...x, price:Number(x.price||0)}));}; }
function openSaleForm(obj) { if(!data.contacts.length) return alert('Bitte zuerst einen Kontakt hinzufügen.'); if(!data.products.length) return alert('Bitte zuerst ein Produkt hinzufügen.'); modal(obj?'Sale bearbeiten':'Sale hinzufügen', `<form id="form">${fields(obj,'sale')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); const form=$('#form'); const updateTotal=()=>{ form.totalPriceDisplay.value=money(Number(form.quantity.value||1)*Number(form.unitPrice.value||0)); }; $('[data-product-select]', form).onchange=e=>{ const price=e.target.selectedOptions[0]?.dataset.price; if(price) form.unitPrice.value=price; updateTotal(); }; $('[data-sale-quantity]', form).oninput=updateTotal; $('[data-sale-unit-price]', form).oninput=updateTotal; form.onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'sales',x=>{ const quantity=Math.max(1, Number(x.quantity||1)); const unitPrice=Number(x.unitPrice||0); const totalPrice=quantity*unitPrice; delete x.totalPriceDisplay; return {...x, quantity, unitPrice, totalPrice, price:totalPrice, currency:'CHF', companyId:contactById(x.contactId)?.companyId||''}; });}; }
function openFollowForm(obj) { if(!data.companies.length) return alert('Bitte zuerst eine Firma hinzufügen.'); modal(obj?'Follow-up bearbeiten':'Follow-up hinzufügen', `<form id="form">${fields(obj,'follow')}<div class="actions" style="margin-top:16px"><button class="btn primary">Speichern</button></div></form>`); $('#form').onsubmit=e=>{e.preventDefault();handleForm(e.target,obj,'followUps',x=>({...x, title:x.type || 'Follow-up', completedAt:x.status==='Erledigt'?(obj?.completedAt||isoNow()):''}));}; }
function confirmDelete(message, cb) { if (confirm(`${message}\nDiese Aktion kann nicht rückgängig gemacht werden.`)) cb(); }
render();
